Adding the Java part :)
SUSE-Developer-Community/sandbox-welcome-content pull request #68
Opened 2020-03-13 13:08 UTC by Rasadus03

2020-03-16 10:19 UTC, timirnich requested changes
A very good start, thank you very much! Suggesting a couple of minor edits...

2020-03-16 10:19 UTC, timirnich commented on content/cli.md
> +First let us go to the spring initializer site https://start.spring.io/ the select the required dependcies and enter the project name and details, here are the requested details:
```suggestion
First let us go to the spring initializer site https://start.spring.io/ and select the required dependencies. Enter the project name and details as follows:
```

2020-03-16 10:19 UTC, timirnich commented on content/cli.md
> +  Upzip the project then open eclipse and import the project.
```suggestion
  Upzip the project, then open eclipse and import the project.
```

2020-03-16 10:19 UTC, timirnich commented on content/cli.md
> +  Now Navigate to com.suse.cap.helloworld and there create HelloWorldController with the following content:
```suggestion
  Now navigate to com.suse.cap.helloworld and there create HelloWorldController with the following content:
```

2020-03-16 10:19 UTC, timirnich commented on content/cli.md
> +Then navigate to the main folder and create manifest.yaml with the following content:
```suggestion
Then navigate to the main folder and create `manifest.yaml` with the following content:
```

2020-03-16 10:19 UTC, timirnich commented on content/cli.md
> +Now try to build the application using maven by running mvn clean install then pushing it into the application by cf push and test it but running the browser your application assigned route followed
```suggestion
Now try to build the application using maven by running `mvn clean install` then pushing it into the application by `cf push` and test it but pointing your browser to your application's assigned route followed by `helloworld/sayHello/<your username>` and you can see the Hello World message.
```

2020-03-17 10:55 UTC, Rasadus03 commented
> A very good start, thank you very much! Suggesting a couple of minor edits...

Thanks alot Tim for the review changes applied :).

2020-03-17 11:24 UTC, timirnich approved these changes
Thanks @Rasadus03! Will merge now...

2020-03-17 11:24 UTC, merged

2020-03-17 11:25 UTC, timirnich commented
@Rasadus03 please delete the topic branch if you don't need it anymore.

2020-03-17 12:20 UTC, Rasadus03 commented
Deleted the Fork thanks @timirnich  :)

2020-03-17 12:55 UTC, timirnich commented
@Rasadus03 thanks, my comment assumed you had created a topic branch in this repo. A second later I realised my error and hence deleted the comment. We're trying to limit the number of existing branches over here to avoid getting lost. Keeping a fork would have been fine of course but thanks for being reactive!